const SCALE_BY = 1.09;
const MAX_SCALE = 6;
const MIN_SCALE = 0.09;
const POSITION_THRESHOLD = 100;
const ROTATION_THRESHOLD = 30;
const EQUATORIAL_RADIUS = 6378200;
const POLAR_RADIUS = 6356900

export {
    SCALE_BY,
    MAX_SCALE,
    MIN_SCALE,
    POSITION_THRESHOLD,
    ROTATION_THRESHOLD,
    EQUATORIAL_RADIUS,
    POLAR_RADIUS
}